# Generated by Django 3.1.5 on 2021-04-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(help_text='Enter a show genre (e.g. Science Fiction)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('release', models.IntegerField(default=2021, max_length=4)),
                ('rating', models.FloatField()),
                ('seasons', models.IntegerField()),
                ('actor', models.ManyToManyField(help_text='Select actors starring in this show this show', related_name='actors', to='pages.Genre')),
                ('genre', models.ManyToManyField(help_text='Select a genre for this show', related_name='genres', to='pages.Genre')),
            ],
        ),
    ]
