# Generated by Django 3.1.5 on 2021-04-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_actor_genre_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='release',
            field=models.IntegerField(default=2021),
        ),
    ]
