# Generated by Django 3.1.5 on 2021-04-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20210419_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='actor',
            field=models.ManyToManyField(help_text='Select actors starring in this show this show', related_name='actors', to='pages.Actor'),
        ),
    ]
