# Generated by Django 3.1.5 on 2021-04-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20210419_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='pic',
            field=models.ImageField(blank=True, default='placeholder.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='show',
            name='pic',
            field=models.ImageField(blank=True, default='placeholder.png', upload_to=''),
        ),
    ]
