# Generated by Django 3.1.5 on 2021-04-22 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20210422_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='pic',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='pic',
            new_name='picture',
        ),
    ]
